/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;

import Modelo.Detalleventas2;
import Modelo.Login;
import Modelo.Producto;
import Modelo.Ventas2;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import controlador.ControladorCliente;
import controlador.ControladorLogin;
import controlador.ControladorProducto;
import controlador.ControladorVentas2;
import java.awt.List;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import jdk.vm.ci.meta.Assumptions;

/**
 *
 * @author denni
 */
public class frmGestionVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmGestionVentas
     */
    DefaultTableModel modT = new DefaultTableModel();
    Cliente cliente;
    Producto producto = null;
    SpinnerNumberModel spmModel = null;
    Detalleventas2 dv = new Detalleventas2();
    Ventas2 venta2 = new Ventas2();
    ControladorVentas2 conV = new ControladorVentas2();
    Login log;
    
    double totalPagar = 0;
    int idventa=0;
    public frmGestionVentas() {
        initComponents();
        spmModel = new SpinnerNumberModel();
        this.setLocationRelativeTo(null);
        buscarCliente();
        //generaSerie();
        txtNumVen.setText(ControladorVentas2.generarCodigo());
        txtNumVen.setEditable(false);
        spCantidad.setModel(spmModel);
        spCantidad.setEnabled(false);
        //txtVendedor.setText();
        ControladorVentas2.mostrarTitulo(TablaProductos);
        generaFecha();
        
    }
    void generaFecha(){
        Calendar cale = new GregorianCalendar();
        txtFecha.setText("" + cale.get(Calendar.YEAR) +
                "-" + (cale.get(Calendar.MONTH) + 1) + "-" + cale.get(Calendar.DAY_OF_MONTH));
    }
    
    void generaSerie(){
//        String serie = ControladorVentas2.NumSerie();
//        if (serie==null) {
//            txtNumVen.setText("000001");
//        }else{
//            int cont = Integer.parseInt(serie);
//            cont++;
//            txtNumVen.setText("00000"+cont);
//        }
//            
        txtNumVen.setText(ControladorVentas2.generarCodigo());
    }

    String codigoCliente() {
        return txtCodCli.getText();
    }

    int codigoProducto() {
        return Integer.parseInt(txtCodPro.getText());
    }

    int stock() {
        return Integer.parseInt(txtStock.getText());
    }

    double precio() {
        return Double.parseDouble(txtPrecio.getText());
    }

    int cantidadSelecionada() {
        return Integer.parseInt(spCantidad.getValue().toString());
    }

    void buscarCliente() {
        btnBuscarProducto.setEnabled(false);
        btnGenerarVenta.setEnabled(false);
        btnAgregar.setEnabled(false);

    }

    void vendendor(String usuario) {
        txtVendedor.setText(usuario);
    }

    void mostrarProducto() {
        producto = new Producto(codigoProducto());
        frmAgregarPro fproducto = new frmAgregarPro();
        if (ControladorProducto.buscarProducto(producto, txtProducto, txtPrecio, txtStock)) {
            JOptionPane.showMessageDialog(rootPane, "Producto encontrado");
            spCantidad.setEnabled(true);
            int cantidad = ControladorVentas2.cantidadMaxima(producto.getIdPro());
            spmModel = new SpinnerNumberModel();

            spmModel.setMaximum(cantidad);
            spmModel.setMinimum(0);
            spmModel.setStepSize(1);

            spCantidad.setModel(spmModel);
        } else {
            JOptionPane.showMessageDialog(rootPane, "producto no encontrado");
            fproducto.setVisible(true);
        }
    }

    String validar() {
        if (txtCliente.getText() == "" || txtCodCli.getText() == "") {
            return "rellenar los campos requeridos";
        } else if (txtProducto.getText() == "" || txtCodPro.getText() == "") {
            return "rellenar los campos de productos";
        }else if (cantidadSelecionada()==0) {
            return "la cantidad debe ser mayor a 0";
        }
        else {
            return "";
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void tema() {
        try {
            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    public void mostrarCliente() {
        this.cliente = new Cliente(codigoCliente());
        frmCliente fCliente = new frmCliente();
        if (ControladorCliente.buscarCliente(this.cliente, txtCliente)) {
            JOptionPane.showMessageDialog(null, "encontrado");
            btnBuscarProducto.setEnabled(true);
            txtCodCli.setEditable(false);
            txtCodPro.requestFocus();
            this.cliente= ControladorCliente.buscarClienteget(cliente, txtCliente);
            
        } else {
            JOptionPane.showMessageDialog(null, "no encontrado, registrar nuevo cliente");
            fCliente.dni(cliente.getDni());

            fCliente.setVisible(true);

        }
    }
    
    String fecha() {
        Calendar calendario = new GregorianCalendar();
        String fecha = "" + calendario.get(Calendar.YEAR) + "/" + (calendario.get(Calendar.MONTH)+1) + "/" + calendario.get(Calendar.DAY_OF_MONTH);
        return fecha;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumVen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodCli = new javax.swing.JTextField();
        txtCodPro = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        spCantidad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("GESTION DE VENTAS");

        jLabel2.setText("Tel: 950565875");

        jLabel3.setText("Nro SERIE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumVen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel4.setText("COD CLIENTE:");

        jLabel5.setText("COD PRODU:");

        jLabel6.setText("PRECIO:");

        jLabel7.setText("CANTIDAD:");

        txtCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodCliActionPerformed(evt);
            }
        });
        txtCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodCliKeyReleased(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel8.setText("CLIENTE:");

        jLabel9.setText("PRODUC:");

        jLabel10.setText("STOCK:");

        jLabel11.setText("VENDEDOR:");

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodPro)
                            .addComponent(txtPrecio)
                            .addComponent(spCantidad))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarCliente)
                            .addComponent(btnBuscarProducto)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVendedor))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(jLabel8)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto)
                    .addComponent(jLabel9)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(jLabel10)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NRO", "COD", "PRODUCTO ", "CANTIDAD", "P. UNIT", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCancelar.setText("CANCELAR");

        btnGenerarVenta.setText("GENERAR VENTA");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });

        jLabel12.setText("TOTAL A PAGAR:");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarVenta)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGenerarVenta)
                        .addComponent(btnCancelar)
                        .addComponent(jButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        mostrarCliente();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        mostrarProducto();
        btnAgregar.setEnabled(true);
//        producto = new Producto(codigoProducto());

    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void txtCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodCliActionPerformed

    }//GEN-LAST:event_txtCodCliActionPerformed

    private void txtCodCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodCliKeyReleased
        if (txtCodCli.getText().length() == 8) {
            mostrarCliente();
        }

    }//GEN-LAST:event_txtCodCliKeyReleased

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        // ControladorVentas.mostrarTabla(TablaProductos,dv);
        
            
                if (validar().equals("")){
                
                agregaar();
            }
            
        else{
            JOptionPane.showMessageDialog(rootPane,validar());
        }
            
        // TODO add your handling code here:
        btnGenerarVenta.setEnabled(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        // TODO add your handling code here:
//        if (txtTotal.getText().equals("")) {
//            JOptionPane.showMessageDialog(rootPane,"debe ingresar datos");
//            
//        }else{
            
        guardarVenta();
        guardarDetalle();
        //actializarStock(); esta parte falta hacer 
        ControladorVentas2.limpiarTabla(TablaProductos);
        //item=0;
        JOptionPane.showMessageDialog(rootPane, "se genero la venta");
        generaSerie();
        actualizarStock();
        notaPago();
        
        frmNotaVenta nota = new frmNotaVenta();
        
        nota.idmostrar(idventa);
        nota.setVisible(true);
        //}
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    public void guardarVenta(){
        //int idV =ControladorLogin.obtenetIdA(txtCodPro);
        int idV =1;
        int idC =cliente.getIdCliente();
        //System.out.println("GetIdCliente: " + idC);
        String serie = txtNumVen.getText();
        String fecha = txtFecha.getText();
        double monTotal = Double.parseDouble(txtTotal.getText());
        //venta2 = new Ventas2(idV, serie, fecha, monTotal, idC);
        venta2.setIdAdmin(idV);
        venta2.setNumSerie(serie); 
        venta2.setFecha(fecha);
        venta2.setMonto(monTotal);
        venta2.setIdCliente(idC);
        
        //System.out.println("asd : "+ ControladorVentas2.guardarVenta(venta2));
    }
    public void guardarDetalle(){
      //  System.out.println("asd22323 : "+ ControladorVentas2.guardarVenta(venta2));
        //String idv=String.valueOf(  ControladorVentas2.guardarVenta(venta2) );
        
        int idven = ControladorVentas2.guardarVenta(venta2);
       // dv.setIdDV(idven);
       idventa=idven;
       for (int i = 0; i < TablaProductos.getRowCount(); i++) {
            int idp = Integer.parseInt(TablaProductos.getValueAt(i, 1).toString());
            System.out.println(TablaProductos.getValueAt(i, 4).toString());
            int cantidad = Integer.parseInt(TablaProductos.getValueAt(i, 4).toString());
            double precio = Double.parseDouble(TablaProductos.getValueAt(i, 5).toString());
            //dv = new Detalleventas2(idven, idp, cantidad, precio);
            dv.setIdVen(idven);
            
            //System.out.println("IDventa front itnt" + idven);
            //System.out.println("IDvbent get  " + dv.getIdDV());
            dv.setIdProduc(idp);
            dv.setCantidad(cantidad);
            dv.setPrecioVenta(precio);
            ControladorVentas2.guardarDVenta(dv);
            
        }      
    }

    public void actualizarStock(){// el esta parte falta corregir cuando llamo al metodo el stock se pone en 0 
        for (int i = 0; i < TablaProductos.getRowCount(); i++) {
            int idProducto=Integer.parseInt(TablaProductos.getValueAt(i, 1).toString());
            int cantidadProducto=Integer.parseInt(TablaProductos.getValueAt(i,4).toString());
            int stockPro=ControladorVentas2.getStock(idProducto);
            ControladorVentas2.disminuirStock(cantidadProducto, stockPro, idProducto);
            
            
            
        }
    }
    void notaPago(){
        String numeroSerie=txtNumVen.getText();
        String cliente=txtCliente.getText();
        String fecha=txtFecha.getText();
        frmNotaVenta nota= new frmNotaVenta();
        nota.reporte(numeroSerie, cliente, fecha, "", "", "", "", "");
        for (int i = 0; i < TablaProductos.getRowCount(); i++) {
            String producto=TablaProductos.getValueAt(i, 2).toString();
            String precio=TablaProductos.getValueAt(i, 3).toString();
            String cantidad=TablaProductos.getValueAt(i, 4).toString();
            String total=TablaProductos.getValueAt(i, 5).toString();
            nota.reporte("", "", "", producto, precio, cantidad, total, "");
            
        }
        
        nota.setVisible(true);
    }
            
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed
   int item=0;
     
    void agregaar() {
        String nombreP = txtProducto.getText();

        int codigoPro = codigoProducto();
        double precio = precio();
        int cantidad = cantidadSelecionada();
        //dv=new DetalleVentas(codigoPro, cantidad, precio);
        ArrayList lis = new ArrayList();
        double total = cantidad * precio;
        ControladorVentas2.mostrarTitulo(TablaProductos);
        String[] titulo = {"Nro", "codigo", "producto", "P.unitario", "cantidad", "total"};
        modT.setColumnIdentifiers(titulo);
        
        item++;
        if (stock() > 0) {

            lis.add(item);
            lis.add(codigoPro);
            lis.add(nombreP);
            lis.add(precio());
            lis.add(cantidad);
            lis.add(total);
            Object fila[] = {
                lis.get(0),
                lis.get(1),
                lis.get(2),
                lis.get(3),
                lis.get(4),
                lis.get(5)
                    
            };
            txtStock.setText(String.valueOf(stock()-cantidadSelecionada()));
            
            modT.addRow(fila);
        }else{
            JOptionPane.showMessageDialog(rootPane,"stock insuficiente");
        }
        TablaProductos.setModel(modT);
        calcularTotal();
    }
    
    void calcularTotal(){
      
        double total = 0;
        for (int i = 0; i < TablaProductos.getRowCount(); i++) {
            total += Double.parseDouble((modT.getValueAt(i, 5).toString()));
        }
        txtTotal.setText(String.valueOf(total));
      
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGestionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tema();
                new frmGestionVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodCli;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumVen;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
