/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Login;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.UIManager;

/**
 *
 * @author MASTER
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu3
     */
    
    Login mosL = new Login();
    int xMouse;
    int yMouse;
    public frmMenu() {
        initComponents();
        this.setSize(1100, 630);
        this.setLocationRelativeTo(null);
        btnUsuario.setVisible(true);
        this.btnCerrarSecion.setVisible(false);
        //this.txtMosUsuario.setText("");
        cambiarCursor();
    }
   void cambiarCursor(){
        btnAgregarPro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnSistemaVenta.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnUsuario.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnReportes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnRegistaAdmi.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrarSecion.setCursor(new Cursor(Cursor.HAND_CURSOR));
   }
   String usuario(){
       return txtMosUsuario.getText();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSecion = new javax.swing.JPanel();
        txtCerrarSecion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMosUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarPro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSistemaVenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistaAdmi = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCerrarSecion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSecion.setOpaque(false);
        btnCerrarSecion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSecionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSecionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSecionMouseExited(evt);
            }
        });

        txtCerrarSecion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarsesion.png"))); // NOI18N
        txtCerrarSecion.setText(" Cerrar Seccion");

        javax.swing.GroupLayout btnCerrarSecionLayout = new javax.swing.GroupLayout(btnCerrarSecion);
        btnCerrarSecion.setLayout(btnCerrarSecionLayout);
        btnCerrarSecionLayout.setHorizontalGroup(
            btnCerrarSecionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSecionLayout.createSequentialGroup()
                .addComponent(txtCerrarSecion, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCerrarSecionLayout.setVerticalGroup(
            btnCerrarSecionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCerrarSecion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(btnCerrarSecion);
        btnCerrarSecion.setBounds(970, 50, 122, 24);

        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NOMBRE DE LA EMPRESA");

        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuario.setOpaque(false);
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtMosUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMosUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMosUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuarioLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtMosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 623, Short.MAX_VALUE)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 20, 1100, 30);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarPro.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarPro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarPro.setText("AGREGAR PRODUCTO");
        btnAgregarPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 12, -1, 58));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar - copia.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 12, 58, 58));

        btnSistemaVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnSistemaVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSistemaVenta.setText("SISTEMA DE VENTA");
        btnSistemaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSistemaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSistemaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 76, 164, 55));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte - copia.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 58, 56));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta - copia.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 58, 58));

        btnRegistaAdmi.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistaAdmi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistaAdmi.setText("REGISTRAR ADMINISTRADORES");
        btnRegistaAdmi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistaAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistaAdmiActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistaAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 58));

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 231, 58));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono Admi 2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 58, 56));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 100, 324, 310);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo - copia.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1100, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
        // TODO add your handling code here:
        if (btnCerrarSecion.isVisible()) {
            btnCerrarSecion.setVisible(false);
        }else{
            btnCerrarSecion.setVisible(true);
        }
    }//GEN-LAST:event_btnUsuarioMouseClicked

    private void btnUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseEntered
        // TODO add your handling code here:
        btnUsuario.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_btnUsuarioMouseEntered

    private void btnUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseExited
        // TODO add your handling code here:
        btnUsuario.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnUsuarioMouseExited

    private void btnCerrarSecionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSecionMouseClicked
        // TODO add your handling code here:
        this.dispose();
        frmLogin log = new frmLogin();
        log.setVisible(true);
    }//GEN-LAST:event_btnCerrarSecionMouseClicked

    private void btnCerrarSecionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSecionMouseEntered
        // TODO add your handling code here:
        btnCerrarSecion.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnCerrarSecionMouseEntered

    private void btnCerrarSecionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSecionMouseExited
        // TODO add your handling code here:
        btnCerrarSecion.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btnCerrarSecionMouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnRegistaAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistaAdmiActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        frmRegistrarAdmi RAdmin = new frmRegistrarAdmi();
        RAdmin.setVisible(true);
    }//GEN-LAST:event_btnRegistaAdmiActionPerformed

    private void btnAgregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProActionPerformed
        frmAgregarPro producto=new frmAgregarPro();
        producto.setVisible(true);
   //     this.dispose();
    }//GEN-LAST:event_btnAgregarProActionPerformed

    private void btnSistemaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaVentaActionPerformed
        // TODO add your handling code here:
        frmGestionVentas venta=new frmGestionVentas();
        venta.vendendor(usuario());
        venta.setVisible(true);
        
    }//GEN-LAST:event_btnSistemaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new AluminiumLookAndFeel());
                } catch (Exception e) {
                }
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPro;
    private javax.swing.JPanel btnCerrarSecion;
    private javax.swing.JButton btnRegistaAdmi;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSistemaVenta;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCerrarSecion;
    public static transient volatile javax.swing.JLabel txtMosUsuario;
    // End of variables declaration//GEN-END:variables
}
